"""基础层 — 无内部依赖的底层模块

包含：utils（路径工具）、logger（日志系统）、models（数据模型）、game_data（游戏坐标）
"""

from .utils import (
    get_project_root,
    get_src_dir,
    get_config_dir,
    get_cache_dir,
    get_data_dir,
    get_3rd_party_dir,
    get_client_config_path,
    ensure_path,
    ensure_src_path,
    ensure_project_path,
    get_adb_path,
    get_git_path,
    get_standard_flows_config_path,
    get_logging_config_path,
)

from .logger import (
    ClientLogger,
    LogLevel,
    LogCategory,
    LogRecord,
    LogFormatter,
    JSONLogFormatter,
    LogHandler,
    ConsoleHandler,
    FileHandler,
    GUIHandler,
    LogRotator,
    PerformanceMonitor,
    get_logger,
    init_logger,
)

from .models import (
    ElementType,
    VerificationStatus,
    ElementKnowledge,
    ElementVerification,
    PageKnowledge,
    TaskStatus,
    TaskCycle,
    TaskDefinition,
    TaskInstance,
    EventActivity,
    AnalysisResult,
    make_semantic_id,
    PageState,
    UIElement,
    PageNode,
    PageEdge,
    PageTree,
    hash_screenshot,
    hash_element,
)

from .game_data import (
    SCREEN_WIDTH,
    SCREEN_HEIGHT,
    ADB_WIDTH,
    ADB_HEIGHT,
    TOP_BAR_Y_RANGE,
    OVERLAY_ROI,
    Coords,
    TOP_BAR_BUTTONS,
    NAVIGATION_MAP,
    OVERLAY_KEYWORDS,
    PAGE_TYPE_KEYWORDS,
    xy_str,
    lookup_button,
    coords_for_model,
)

__all__ = [
    # utils
    "get_project_root",
    "get_src_dir",
    "get_config_dir",
    "get_cache_dir",
    "get_data_dir",
    "get_3rd_party_dir",
    "get_client_config_path",
    "ensure_path",
    "ensure_src_path",
    "ensure_project_path",
    "get_adb_path",
    "get_git_path",
    "get_standard_flows_config_path",
    "get_logging_config_path",
    # logger
    "ClientLogger",
    "LogLevel",
    "LogCategory",
    "LogRecord",
    "LogFormatter",
    "JSONLogFormatter",
    "LogHandler",
    "ConsoleHandler",
    "FileHandler",
    "GUIHandler",
    "LogRotator",
    "PerformanceMonitor",
    "get_logger",
    "init_logger",
    # models
    "ElementType",
    "VerificationStatus",
    "ElementKnowledge",
    "ElementVerification",
    "PageKnowledge",
    "TaskStatus",
    "TaskCycle",
    "TaskDefinition",
    "TaskInstance",
    "EventActivity",
    "AnalysisResult",
    "make_semantic_id",
    "PageState",
    "UIElement",
    "PageNode",
    "PageEdge",
    "PageTree",
    "hash_screenshot",
    "hash_element",
    # game_data
    "SCREEN_WIDTH",
    "SCREEN_HEIGHT",
    "ADB_WIDTH",
    "ADB_HEIGHT",
    "TOP_BAR_Y_RANGE",
    "OVERLAY_ROI",
    "Coords",
    "TOP_BAR_BUTTONS",
    "NAVIGATION_MAP",
    "OVERLAY_KEYWORDS",
    "PAGE_TYPE_KEYWORDS",
    "xy_str",
    "lookup_button",
    "coords_for_model",
]
